{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Comparativo de Votos A e B",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_votos_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total de Votos B",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_votos_total{opcao=\"b\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Votos A",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_votos_total{opcao=\"a\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}